name: Feature Request
description: Suggest an idea for the project
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the feature
      description: What should the frock do?
    validations:
      required: true
  - type: checkboxes
    id: platforms
    attributes:
      label: Target Platforms
      options:
        - label: Windows
        - label: Linux (Debian/Fedora KDE)
        - label: Android
  - type: upload
    id: design
    attributes:
      label: Mockups or UI Ideas
      description: If you have a sketch or a reference image of how this should look, upload it here.
  - type: checkboxes
    id: verification
    attributes:
      label: Verification
      options:
        - label: I have checked that I'm running the app in a supported environment.
          required: true
        - label: I have checked that this feature hasn't been requested already.
          required: true
